name: Driver compile check

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build x64 driver
        shell: powershell
        run: |
          .\scripts\build-driver.ps1
